HOST_ARCH       ?= $(shell uname -m | sed -e s/arm.*/arm/ -e s/aarch64.*/arm64/)
ARCH            ?= $(shell uname -m | sed -e s/arm.*/arm/ -e s/aarch64.*/arm64/)
PWD             ?= ${shell pwd}
BUILD_DIR       ?= $(shell pwd)
_BUILD_DIR      ?= $(shell readlink -f $(BUILD_DIR))
EXTRA_MAKE_FLAGS =

INST_PACKAGE_NAME     ?=  $(shell cat dkms.conf | grep 'PACKAGE_NAME' | cut -d '=' -f 2 | cut -d '"' -f 2 )
INST_PACKAGE_VERSION  ?=  $(shell cat dkms.conf | grep 'PACKAGE_VERSION' | cut -d '=' -f 2 | cut -d '"' -f 2 )

TIER4_ISX021_FIRMWARE_BINARY := tier4-isx021.bin

DEST_FIRMWARE_DIR    := /lib/firmware
SRC_FIRMWARE_BINARY  := /usr/src/$(INST_PACKAGE_NAME)-$(INST_PACKAGE_VERSION)/$(TIER4_ISX021_FIRMWARE_BINARY)
DEST_FIRMWARE_BINARY := $(DEST_FIRMWARE_DIR)/$(TIER4_ISX021_FIRMWARE_BINARY)

L4T_RELEASE_MAIN  := $(shell head -n 1 /etc/nv_tegra_release | cut -d ' ' -f 2 )
L4T_RELEASE_MAJOR := $(shell head -n 1 /etc/nv_tegra_release | cut -d ' ' -f 5 | cut -d ',' -f 1 | cut -d '.' -f 1 )
L4T_RELEASE_MINOR := $(shell head -n 1 /etc/nv_tegra_release | cut -d ' ' -f 5 | cut -d ',' -f 1 | cut -d '.' -f 2 )
L4T_RELEASE       := $(L4T_RELEASE_MAIN).$(L4T_RELEASE_MAJOR).$(L4T_RELEASE_MINOR)
KERNELRELEASE     := $(shell uname -r)
KERNEL_SRC_DIR    := /lib/modules/$(shell uname -r)/build

$(warning L4T_RELEASE_MAIN  = $(L4T_RELEASE_MAIN))
$(warning L4T_RELEASE_MAJOR = $(L4T_RELEASE_MAJOR))
$(warning L4T_RELEASE_MINOR = $(L4T_RELEASE_MINOR))
$(warning L4T_RELEASE    = $(L4T_RELEASE))
$(warning KERNELRELEASE  = $(KERNELRELEASE))
$(warning KERNEL_SRC_DIR = $(KERNEL_SRC_DIR))

TARGET_ISX021_DTS               := tier4-isx021-gmsl-device-tree-overlay-dlap212-r364
TARGET_IMX490_DTS               := tier4-imx490-gmsl-device-tree-overlay-dlap212-r364
TARGET_IMX728_DTS               := tier4-imx728-gmsl-device-tree-overlay-dlap212-r364
TARGET_ISX021_IMX490_DTS        := tier4-isx021-imx490-gmsl-device-tree-overlay-dlap212-r364
TARGET_ISX021_IMX490_IMX728_DTS := tier4-isx021-imx490-imx728-gmsl-device-tree-overlay-dlap212-r364
TARGET_IMX490_IMX728_DTS        := tier4-imx490-imx728-gmsl-device-tree-overlay-dlap212-r364
MAKE_OVERLAY_DTS_CMD            := make_overlay_dts_dlap212-orin-nx-r36.py r36.4

$(warning TARGET_ISX021_DTS               = $(TARGET_ISX021_DTS))
$(warning TARGET_IMX490_DTS               = $(TARGET_IMX490_DTS))
$(warning TARGET_IMX728_DTS               = $(TARGET_IMX728_DTS))
$(warning TARGET_ISX021_IMX490_DTS        = $(TARGET_ISX021_IMX490_DTS))
$(warning TARGET_ISX021_IMX490_IMX728_DTS = $(TARGET_ISX021_IMX490_IMX728_DTS))
$(warning TARGET_IMX490_IMX728_DTS        = $(TARGET_IMX490_IMX728_DTS))


ccflags-y += -DBUILD_STAMP="\"`date +'%Y-%m-%d %H:%M:%S'`\""

obj-m := tier4-max9295.o tier4-max9296.o tier4-isx021.o tier4-imx490.o tier4-imx728.o tier4-gw5300.o tier4-fpga.o max20089.o

# ------------------------------------------------

.PHONY: all
all: binary_module modules dtbo

modules:
	$(MAKE) -C $(KERNEL_SRC_DIR) ARCH=$(ARCH) M=$(BUILD_DIR) src=$(PWD) $(EXTRA_MAKE_FLAGS) modules

binary_module:
	install -d $(DEST_FIRMWARE_DIR)
	sudo cp -f $(SRC_FIRMWARE_BINARY) $(DEST_FIRMWARE_BINARY)

$(TARGET_ISX021_DTS).dts:
	python3 ./$(MAKE_OVERLAY_DTS_CMD) -8 C1
$(TARGET_IMX490_DTS).dts:
	python3 ./$(MAKE_OVERLAY_DTS_CMD) -8 C2
$(TARGET_IMX728_DTS).dts:
	python3 ./$(MAKE_OVERLAY_DTS_CMD) -8 C3
$(TARGET_ISX021_IMX490_DTS).dts:
	python3 ./$(MAKE_OVERLAY_DTS_CMD) -2 C1 -2 C2 -2 C1 -2 C2
$(TARGET_ISX021_IMX490_IMX728_DTS).dts:
	python3 ./$(MAKE_OVERLAY_DTS_CMD) -2 C1 -2 C2 -4 C3
$(TARGET_IMX490_IMX728_DTS).dts:
	python3 ./$(MAKE_OVERLAY_DTS_CMD) -4 C2 -4 C3

ifeq ($(L4T_RELEASE_MAIN), R34)
	sed -i -e '/^ *jetson-header-name/s/AGX  *CSI/AGX Xavier CSI/' $(TARGET_ISX021_DTS).dts
	sed -i -e '/^ *jetson-header-name/s/AGX  *CSI/AGX Xavier CSI/' $(TARGET_IMX490_DTS).dts
	sed -i -e '/^ *jetson-header-name/s/AGX  *CSI/AGX Xavier CSI/' $(TARGET_IMX728_DTS).dts
	sed -i -e '/^ *jetson-header-name/s/AGX  *CSI/AGX Xavier CSI/' $(TARGET_ISX021_IMX490_DTS).dts
	sed -i -e '/^ *jetson-header-name/s/AGX  *CSI/AGX Xavier CSI/' $(TARGET_ISX021_IMX490_IMX728_DTS).dts
	sed -i -e '/^ *jetson-header-name/s/AGX  *CSI/AGX Xavier CSI/' $(TARGET_IMX490_IMX728_DTS).dts
else ifeq ($(L4T_RELEASE_MAIN), R35)
	sed -i -e '/^ *jetson-header-name/s/AGX Xavier CSI/AGX CSI/' $(TARGET_ISX021_DTS).dts
	sed -i -e '/^ *jetson-header-name/s/AGX Xavier CSI/AGX CSI/' $(TARGET_IMX490_DTS).dts
	sed -i -e '/^ *jetson-header-name/s/AGX Xavier CSI/AGX CSI/' $(TARGET_IMX728_DTS).dts
	sed -i -e '/^ *jetson-header-name/s/AGX Xavier CSI/AGX CSI/' $(TARGET_ISX021_IMX490_DTS).dts
	sed -i -e '/^ *jetson-header-name/s/AGX Xavier CSI/AGX CSI/' $(TARGET_ISX021_IMX490_IMX728_DTS).dts
	sed -i -e '/^ *jetson-header-name/s/AGX Xavier CSI/AGX CSI/' $(TARGET_IMX490_IMX728_DTS).dts
endif

# Here we disable parallel build in order to rebuild the dts files step by step
.NOTPARALLEL:
dtbo: clean_dts $(TARGET_ISX021_DTS).dts $(TARGET_IMX490_DTS).dts $(TARGET_IMX728_DTS).dts  $(TARGET_ISX021_IMX490_DTS).dts $(TARGET_ISX021_IMX490_IMX728_DTS).dts $(TARGET_IMX490_IMX728_DTS).dts
	dtc -O dtb -o $(TARGET_ISX021_DTS).dtbo -@ $(TARGET_ISX021_DTS).dts
	dtc -O dtb -o $(TARGET_IMX490_DTS).dtbo -@ $(TARGET_IMX490_DTS).dts
	dtc -O dtb -o $(TARGET_IMX728_DTS).dtbo -@ $(TARGET_IMX728_DTS).dts
	dtc -O dtb -o $(TARGET_ISX021_IMX490_DTS).dtbo -@ $(TARGET_ISX021_IMX490_DTS).dts
	dtc -O dtb -o $(TARGET_ISX021_IMX490_IMX728_DTS).dtbo -@ $(TARGET_ISX021_IMX490_IMX728_DTS).dts
	dtc -O dtb -o $(TARGET_IMX490_IMX728_DTS).dtbo -@ $(TARGET_IMX490_IMX728_DTS).dts
	cp -rf $(TARGET_ISX021_DTS).dtbo /boot
	cp -rf $(TARGET_IMX490_DTS).dtbo /boot
	cp -rf $(TARGET_IMX728_DTS).dtbo /boot
	cp -rf $(TARGET_ISX021_IMX490_DTS).dtbo /boot
	cp -rf $(TARGET_ISX021_IMX490_IMX728_DTS).dtbo /boot
	cp -rf $(TARGET_IMX490_IMX728_DTS).dtbo /boot

clean_dts:
	# clean dts to make sure the dts file will be re-built everytime
	rm -f $(TARGET_ISX021_DTS).dts
	rm -f $(TARGET_IMX490_DTS).dts
	rm -f $(TARGET_IMX728_DTS).dts
	rm -f $(TARGET_ISX021_IMX490_DTS).dts
	rm -f $(TARGET_ISX021_IMX490_IMX728_DTS).dts
	rm -f $(TARGET_IMX490_IMX728_DTS).dts

clean:
	$(MAKE) -C $(KERNEL_SRC_DIR) ARCH=$(ARCH) M=$(BUILD_DIR) src=$(PWD) clean
